### ISSUE TITLE
Search bar is buggy; disappears on tap

### ISSUE THREAD

**Issue by vnev** [vnev/PurdueIO#14]
**Normally**:

![one](http://i.imgur.com/pAOuPT2.png)

**When tapped**:

![two](http://i.imgur.com/hbrlH8l.png)

**When something is typed in**:

![three](http://i.imgur.com/AHDzQEt.png)

Fixing the colors and displaying more stuff in the search table should be easy enough to fix, but this search bar is being a real bitch to fix. I couldn't find any definitive answers on StackOverflow (people seem to be having different variations of the same problem). @sanjeetsuhag ideas?

**Comment by sanjeetsuhag** [comment]
Using two `UINavigationControllers` is probably causing this. Could be probably be fixed by using the `presentViewController` method but that may cause more issues due to search logic being linked to `ViewController` switches.

**Comment by vnev** [comment]
:+1:

**Comment by sanjeetsuhag** [comment]
Fixed.

**Comment by vnev** [comment]
:+1:
