### ISSUE TITLE
Remove curses from README file

### ISSUE THREAD

**Issue by felixangell** [vnev/PurdueIO#3]
Hi, I find it really offensive that you curse in the readme, what if my child was looking at this application for a university in another country?

Here's the offender:
> Here's a really shit GIF of it working:

Taken from the README.md file, also there is various curse words in the comments of the [source code](https://github.com/vnev/PurdueIO/blob/fd0209db8599338235e1d2c737a084b38f15a619/PurdueIO/SubjectTableViewController.m#L62).

Please fix this issue immediately. 
<img src="https://assets-cdn.github.com/images/icons/emoji/shipit.png" width="100%">

**Comment by vnev** [comment]
Hi @felixangell,

I would first like to thank you for your interest in the application. That being said, if you "child" is in university, I would think that he knows much worse curse words. If you're really this naive, then you can go fuck yourself. Thanks <3

**Comment by felixangell** [comment]
@vnev you're fired

**Comment by vnev** [comment]
get the fuck out of my repo

**Comment by felixangell** [comment]
**SOFTWARE DEVELOPER PRACTICE?**
