### ISSUE TITLE
Pull down to refresh

### ISSUE THREAD

**Issue by vnev** [vnev/PurdueIO#30]
I'm thinking if this is a good idea or if it might be redundant considering the classes don't move around much. I doubt the classes are going to go over some major rework overnight. Still wondering if this is a handy thing to have or not. Thoughts @sanjeetsuhag?

**Comment by sanjeetsuhag** [comment]
I think that a 'Pull to Refresh' implies that new data will be added frequently, therefore, I believe it'll be a bad design choice.
